CompletKitInstall/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CompletKitInstall.ViewModels
{
    public class CategoryViewModel:IUIObject
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        public DateTimeOffset DateCreated { get; set; }

    }
}

CompletKitInstall/Pages/AddProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CompletKitInstall.Data;
using CompletKitInstall.Repositories;
using CompletKitInstall.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CompletKitInstall.Pages
{
    [Authorize(Roles = "Administrators,Managers")]
    public class AddProductModel : PageModel
    {
        private readonly IProductRepository _productRepo;
        private readonly IProductImageRepository _productImageRepo;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IComplexOperationsHandler _complexOperationsHandler;
        private readonly ILogger<AddProductModel> _logger;
        [BindProperty]
        public IEnumerable<ProductViewModel> Products { get; private set; }
        [BindProperty]
        public List<ProductImageViewModel> ProductImages { get; private set; }
        [BindProperty]
        public IEnumerable<CategoryViewModel> Categories { get; private set; }
        [BindProperty]
        public ProductViewModel Product { get; set; }
        [Required]
        [BindProperty]
        public IFormFile Image { get; set; }
        [BindProperty]
        public IFormFileCollection CatalogImages { get; set; }
        public AddProductModel(IProductRepository productRepo, IProductImageRepository productImageRepo, IWebHostEnvironment webHostEnvironment, ICategoryRepository categoryRepository, IComplexOperationsHandler complexOperationsHandler, ILogger<AddProductModel> logger)
        {
            _productRepo = productRepo;
            _productImageRepo = productImageRepo;
            _webHostEnvironment = webHostEnvironment;
            _categoryRepository = categoryRepository;
            _complexOperationsHandler = complexOperationsHandler;
            _logger = logger;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            return await GetPage();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return await GetPage();
            }

            var pathImg = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Products");
            var pathCtl = Path.Combine(_webHostEnvironment.WebRootPath, "Images/CatalogImages");
            if (!Directory.Exists(pathImg))
            {
                Directory.CreateDirectory(pathImg);
            }

            if (!Directory.Exists(pathCtl))
            {
                Directory.CreateDirectory(pathCtl);
            }

            if (Image.Length > 0)
                try
                {
                    var uniqueFileName = string.Concat(Guid.NewGuid().ToString(), Image.FileName);
                    using var fileStream = new FileStream(Path.Combine(pathImg, uniqueFileName), FileMode.Create);
                    Product.ImageUrl = Path.Combine("Images/Products", uniqueFileName);
                    await Image.CopyToAsync(fileStream);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                    throw ex;
                }
            if (CatalogImages.Count > 0)
            {
                try
                {
                    ProductImages = new List<ProductImageViewModel>();
                    foreach (var image in CatalogImages)
                    {
                        var uniqueFileName = string.Concat(Guid.NewGuid().ToString(), image.FileName);
                        using var fileStream = new FileStream(Path.Combine(pathCtl, uniqueFileName), FileMode.Create);
                        var productImage = new ProductImageViewModel
                        {
                            ImageUrl = Path.Combine("Images/CatalogImages", uniqueFileName),
                        };
                        await image.CopyToAsync(fileStream);
                        ProductImages.Add(productImage);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                    throw ex;
                }
                await _complexOperationsHandler.AddProductAndImages(Product, ProductImages, User);
            }
            else
                await _productRepo.Add(Product, User);

            return RedirectToPage("./AddProduct");
        }
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            try
            {
                var imgPath = _productRepo.GetById(id).Result.ImageUrl;
                var images = await _productImageRepo.GetByProductId(id);
                var ctlImagePaths = new List<string>();
                foreach (var img in images)
                {
                    ctlImagePaths.Add(Path.Combine(_webHostEnvironment.WebRootPath, img.ImageUrl));
                }

                await _complexOperationsHandler.RemoveProductWithImages(id, User);

                var prodImg = new FileInfo(Path.Combine(_webHostEnvironment.WebRootPath,imgPath)); 
                prodImg.Refresh();
                if (prodImg.Exists)
               {
                    prodImg.Delete();
                    _logger.LogInformation($"File Deleted {prodImg.Name}");
                }
                foreach (var path in ctlImagePaths)
                {
                    var ctlImg = new FileInfo(path);
                    if (ctlImg.Exists)
                    {
                        ctlImg.Delete();
                        _logger.LogInformation($"File Deleted {ctlImg.Name}");
                    }
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }

            return RedirectToPage("./AddProduct");
        }

        private async Task<IActionResult> GetPage()
        {
            Categories = await _categoryRepository.Get();
            Products = await _productRepo.Get();
            Products = Products.OrderByDescending(x => x.DateCreated);
            return Page();
        }
    }
}

CompletKitInstall/Pages/Category.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CompletKitInstall.Models;
using CompletKitInstall.Repositories;
using CompletKitInstall.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CompletKitInstall.Pages
{
    [Authorize(Roles ="Administrators,Managers")]
    public class CategoryModel : PageModel
    {
        private readonly ICategoryRepository _categoryRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        [BindProperty]
        public IEnumerable<CategoryViewModel> Categories { get; private set; }
        [BindProperty]
        public CategoryViewModel Category { get; private set; }

        public CategoryModel(ICategoryRepository categoryRepo,IWebHostEnvironment webHostEnvironment)
        {
            _categoryRepo = categoryRepo;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            return await GetPage();
        }
        public async Task<IActionResult> OnPostAsync(CategoryViewModel category)
        {
            if (!ModelState.IsValid)
            {
                return await GetPage();
            }
            await _categoryRepo.Add(category,User);
            return await GetPage();
        }

        private async Task<IActionResult> GetPage()
        {
            Categories = await _categoryRepo.Get();
            Categories = Categories.OrderByDescending(x => x.DateCreated);
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            await _categoryRepo.RemoveById(id,User);
            return RedirectToPage("/Category");
        }
    }
}

CompletKitInstall/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CompletKitInstall.Areas.Identity.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CompletKitInstall.Pages
{
    [AllowAnonymous]
    public class ContactModel : PageModel
    {
        private readonly IMailer _emailSender;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        [BindProperty]
        [Required]
        public string UserEmail { get; set; }
        [BindProperty]
        [Required]
        public string EmailBody { get; set; }
        [BindProperty]
        [Required]
        public string EmailSubject { get; set; }

        public ContactModel(IMailer emailSender,SignInManager<IdentityUser> signInManager,UserManager<IdentityUser> userManager)
        {
            _emailSender = emailSender;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            //await Task.CompletedTask;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();
            else
            {
                var destEmail = "office.cki@yahoo.com";
                EmailBody = EmailBody + "\n" + $"This Email was sent to you from {UserEmail}.";
                await _emailSender.SendMailAsync(destEmail, EmailSubject, EmailBody);
                return RedirectToPage("/Contact");
            }
            

        }

    }
}

CompletKitInstall/Pages/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CompletKitInstall.Repositories;
using CompletKitInstall.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Logging;

namespace CompletKitInstall.Pages
{
    [Authorize(Roles = "Administrators,Managers")]
    public class EditProductModel : PageModel
    {
        private readonly IProductRepository _productRepo;
        private readonly IProductImageRepository _productImageRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<AddProductModel> _logger;

        [BindProperty]
        public ProductViewModel Product { get; set; }
        [BindProperty]
        public List<ProductImageViewModel> ProductImages { get; set; }
        [BindProperty]
        public IFormFileCollection CatalogImages { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }
        public EditProductModel(IProductRepository productRepository, IWebHostEnvironment webHostEnvironment, ILogger<AddProductModel> logger, IProductImageRepository productImageRepository)
        {
            _productRepo = productRepository;
            _productImageRepo = productImageRepository;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            Product = await _productRepo.GetById(id);
            ProductImages = await _productImageRepo.GetByProductId(id);
            return Page();
        }
        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            if (!ModelState.IsValid)
                return Page();
            var pathImg = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Products");
            if (!Directory.Exists(pathImg))
            {
                Directory.CreateDirectory(pathImg);
            }
            if (Image != null)
                if (Image.Length > 0)
                    try
                    {
                        var uniqueFileName = string.Concat(Guid.NewGuid().ToString(), Image.FileName);
                        using var fileStream = new FileStream(Path.Combine(pathImg, uniqueFileName), FileMode.Create);
                        //delete old product image
                        var imgPath = _productRepo.GetById(id).Result.ImageUrl;
                        var prodImg = new FileInfo(Path.Combine(_webHostEnvironment.WebRootPath, imgPath));
                        prodImg.Refresh();
                        if (prodImg.Exists)
                        {
                            prodImg.Delete();
                            _logger.LogInformation($"File Deleted {prodImg.Name}");
                        }
                        Product.ImageUrl = Path.Combine("Images/Products", uniqueFileName);
                        await Image.CopyToAsync(fileStream);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex.Message);
                    }


            await _productRepo.Update(id, Product, User);
            var result = await OnGetAsync(id);
            return result;
        }
        public async Task<IActionResult> OnPostAddImagesAsync()
        {
            var pathCtl = Path.Combine(_webHostEnvironment.WebRootPath, "Images/CatalogImages");
            //if (!ModelState.IsValid)
            //    return Page();
            //CatalogImages = (IFormFileCollection)Request.Form["ctl_Images"].ToList();

            try
            {
                ProductImages = new List<ProductImageViewModel>();
                foreach (var image in CatalogImages)
                {
                    var uniqueFileName = string.Concat(Guid.NewGuid().ToString(), image.FileName);
                    using var fileStream = new FileStream(Path.Combine(pathCtl, uniqueFileName), FileMode.Create);
                    var productImage = new ProductImageViewModel
                    {
                        ImageUrl = Path.Combine("Images/CatalogImages", uniqueFileName),
                        ProductId = Product.Id,
                    };
                    await image.CopyToAsync(fileStream);
                    ProductImages.Add(productImage);
                }
                foreach (var item in ProductImages)
                {
                    await _productImageRepo.Add(item, User);
                }

                var result = await OnPostRefreshImagesAsync(Product.Id);
                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return Page();
                throw ex;
            }
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var prodId = _productImageRepo.GetById(id).Result.ProductId;
            var ctlImagePath = _productImageRepo.GetById(id).Result.ImageUrl;

            try
            {
                await _productImageRepo.RemoveById(id, User);
                var ctlImg = new FileInfo(Path.Combine(_webHostEnvironment.WebRootPath, ctlImagePath));
                ctlImg.Refresh();
                if (ctlImg.Exists)
                {
                    ctlImg.Delete();
                    _logger.LogInformation($"File Deleted {ctlImg.Name}");
                }

                var result = await OnPostRefreshImagesAsync(prodId);
                return result;

            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return Page();
                throw ex;
            }
        }
        public async Task<IActionResult> OnPostRefreshImagesAsync(int id)
        {

            var productImages = await _productImageRepo.GetByProductId(id);
            var result = new PartialViewResult
            {
                ViewName = "~/Pages/Partials/_ProductImagesCardGroup.cshtml",
                ViewData = new ViewDataDictionary<List<ProductImageViewModel>>(ViewData, productImages),
            };
            return result;
        }
    }
}

CompletKitInstall/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CompletKitInstall.Pages
{
    public class ErrorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CompletKitInstall/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CompletKitInstall.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CompletKitInstall/Pages/AddProduct.cshtml
@page
@model CompletKitInstall.Pages.AddProductModel
@{
    ViewData["Title"] = "Add Product";
}
<div class="container mb-1">
    <h2>Create Product</h2>
    <form method="post" class="col-sm-12" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="card col-10 shadow">
            <div class="card-body">
                <div class="form-group">
                    <div class="col-sm-12">
                        <label>Name</label>
                        <span></span>
                    </div>
                    <div>
                        <input class="form-control" asp-for="Product.Name" />
                        <span asp-validation-for="Product.Name" class="text-danger"></span>
                    </div>
                    <div class="col-sm-12">
                        <label>Description</label>
                    </div>
                    <div>
                        <textarea class="form-control" rows="5" asp-for="Product.Description"></textarea>
                        <span asp-validation-for="Product.Description" class="text-danger"></span>
                    </div>
                    <div class="col-sm-12 ">
                        <label>Image</label>
                    </div>
                    <div>
                        <input class="form-control" type="file" asp-for="Image" id="prod_image" onchange="preview_prodimage();" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>
                    <div id="prodimage_preview">

                    </div>
                    <div class="col-sm-12">
                        <label>Categories</label>
                    </div>
                    <div>
                        <select class="form-control" asp-for="Product.CategoryId">
                            <option value="">Choose Category</option>
                            @foreach (var category in @Model.Categories)
                            {
                                <option value="@category.Id.ToString()">@category.Name.ToString()</option>
                            }
                        </select>
                        <span asp-validation-for="Product.CategoryId"></span>
                    </div>
                    <div class="col-sm-12 ">
                        <label>Catalog Images</label>
                    </div>
                    <div class="col-sm-12">
                        <input class="form-control" type="file" multiple="multiple" id="ctl_images" asp-for="CatalogImages" onchange="preview_image();" />
                        <span asp-validation-for="CatalogImages" class="text-danger"></span>
                    </div>
                    <div id="image_preview">

                    </div>

                    <div class="col-sm-12 ">
                        <button type="submit" class="btn-primary" value="Add"> Add </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div>
                <table class="table">
                    <thead>
                        <tr class="table-primary">
                            <th>
                                @Html.DisplayNameFor(model => model.Product.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Product.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Product.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Product.DateCreated)
                            </th>
                            <th>
                                Controls
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Products)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td class="text-truncate" style="max-width: 100px;">
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DateCreated)
                                </td>
                                <td>
                                    <a class="btn btn-outline-secondary" href="/Product/@item.Id">Details</a>
                                    <a class="btn btn-outline-primary" href="/Editproduct/@item.Id">Edit</a>
                                    <button type="submit" asp-page-handler="delete" asp-route-id="@item.Id" class="btn btn-outline-danger" onclick="this.blur();">Delete</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </form>
</div>
<script src="~/js/AddProduct.js"></script>

CompletKitInstall/Pages/Category.cshtml
@page
@model CompletKitInstall.Pages.CategoryModel
@{
    ViewData["Title"] = "Category";
}

<div class="container mb-1">
    <h2>Add Category</h2>
    <form method="post" class="col-sm-12">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="card col-10 shadow">
            <div class="card-body">
                <div class="form-group">
                    <div class="col-sm-12">
                        <label>Name</label>
                        <span></span>
                    </div>
                    <div class="col-sm-12">
                        <input class="form-control" asp-for="Category.Name" />
                        <span asp-validation-for="Category.Name" class="text-danger"></span>
                    </div>
                    <div class="col-sm-12">
                        <label>Description</label>
                    </div>
                    <div class="col-sm-12">
                        <textarea class="form-control" rows="5" asp-for="Category.Description"></textarea>
                        <span asp-validation-for="Category.Description" class="text-danger"></span>
                    </div>
                    <div class="col-sm-12 ">
                        <input type="submit" value="Add" />
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Category.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category.Description)
                </th>
                <th>
                    Controls
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Categories)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <form method="post" enctype="multipart/form-data">
                            <button type="submit" asp-page-handler="delete" asp-route-id="@item.Id" class="btn btn-outline-danger" onclick="this.blur();">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CompletKitInstall/Pages/Contact.cshtml
@page
@model CompletKitInstall.Pages.ContactModel
@{
    ViewData["Title"] = "Contact";
}
<div class="container">
        <div>
            <div>
                <h2>Complet Kit Install</h2>
                <div class=" card col-3">
                    <div class="card-header fs-3">Moisa Andrei
                    </div>
                    <div class="card-body">
                        <p class="text-danger">
                            Administrator
                        </p>
                        <label class="fw-bold">Telefon:</label>
                        <label>074316260</label>
                        <br />
                        <label class="fw-bold">E-mail:s</label>
                        <label class="link-primary">office.cki@yahoo.com</label>
                    </div>
                </div>
            </div>
        </div>
    <h2> Formular de contact </h2>
    <div class="card col-6">
        <form class="m-2" method="post">
            <div>
                <label>Email*</label>
            </div>
            <div class="m-2">
                <input class="form-control" asp-for="UserEmail" />
                <span asp-validation-for="UserEmail" class="text-danger"></span>
            </div>
            <div>
                <label>Subiect*</label>
            </div>
            <div class="m-2">
                <input class="form-control" asp-for="EmailSubject" />
                <span asp-validation-for="EmailSubject" class="text-danger"></span>
            </div>
            <div>
                <label>Mesaj*</label>
            </div>
            <div class="m-2">
                <textarea rows="10" class="form-control" asp-for="EmailBody"></textarea>
                <span asp-validation-for="EmailBody" class="text-danger"></span>
            </div>
            <div class="m-2">
                <button type="submit" class="btn-primary" value="Add"> Trimite </button>
            </div>
        </form>
    </div>
</div>

CompletKitInstall/Pages/EditProduct.cshtml
@page "{id}"
@model CompletKitInstall.Pages.EditProductModel
@{
    ViewData["Title"] = "EditProduct";
}
<div class="container">
    <div class="row align-items-lg-start">
        <div class="col">
            <h2>Edit Product: <a href="/Product/@Model.Product.Id" class="text-primary">@Model.Product.Name</a></h2>
            <div class="col-4">
                <img src="~/@Model.Product.ImageUrl" class="img-thumbnail" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="rounded-2 card col-5 my-1 me-1">
            <div class="card-body">
                <h3>Edit Product</h3>
                <form method="post" enctype="multipart/form-data" asp-page-handler="Edit">
                    <div class="row">
                        <input class="form-control" type="text" asp-for="Product.Name" />
                        <span asp-validation-for="Product.Name"></span>
                    </div>
                    <div class="row">
                        <textarea class="form-control" rows="15" asp-for="Product.Description"></textarea>
                        <span asp-validation-for="Product.Description"></span>
                    </div>
                    <div class="row">
                        <input id="prodImage" type="file" asp-for="Image" class="form-control" onchange="preview_prodimage();" />
                        <span asp-validation-for="Image" />
                    </div>
                    <div class="row" id="prodImagePreview">

                    </div>
                    <div class="row">
                        <button type="submit" class="btn btn-primary col-2" value="Edit"> Edit </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="rounded-2 card col-5 my-1 ms-1">
            <div class="card-body">
                <partial name="Partials/_CatalogImageUpload.cshtml" model="@Model.CatalogImages"/> 
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div id="ProductImages">
                <partial name="Partials/_ProductImagesCardGroup.cshtml" model="@Model.ProductImages" />
            </div>
        </div>
    </div>

</div>