CompletKitInstall/Pages/Category.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CompletKitInstall.Models;
using CompletKitInstall.Repositories;
using CompletKitInstall.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CompletKitInstall.Pages
{
    [Authorize(Roles ="Administrators,Managers")]
    public class CategoryModel : PageModel
    {
        private readonly ICategoryRepository _categoryRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        [BindProperty]
        public IEnumerable<CategoryViewModel> Categories { get; private set; }
        [BindProperty]
        public CategoryViewModel Category { get; private set; }

        public CategoryModel(ICategoryRepository categoryRepo,IWebHostEnvironment webHostEnvironment)
        {
            _categoryRepo = categoryRepo;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            return await GetPage();
        }
        public async Task<IActionResult> OnPostAsync(CategoryViewModel category)
        {
            if (!ModelState.IsValid)
            {
                return await GetPage();
            }
            await _categoryRepo.Add(category,User);
            return await GetPage();
        }

        private async Task<IActionResult> GetPage()
        {
            Categories = await _categoryRepo.Get();
            Categories = Categories.OrderByDescending(x => x.DateCreated);
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            await _categoryRepo.RemoveById(id,User);
            return RedirectToPage("/Category");
        }
    }
}

CompletKitInstall/Pages/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CompletKitInstall.Repositories;
using CompletKitInstall.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Logging;

namespace CompletKitInstall.Pages
{
    [Authorize(Roles = "Administrators,Managers")]
    public class EditProductModel : PageModel
    {
        private readonly IProductRepository _productRepo;
        private readonly IProductImageRepository _productImageRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<AddProductModel> _logger;

        [BindProperty]
        public ProductViewModel Product { get; set; }
        [BindProperty]
        public List<ProductImageViewModel> ProductImages { get; set; }
        [BindProperty]
        public IFormFileCollection CatalogImages { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }
        public EditProductModel(IProductRepository productRepository, IWebHostEnvironment webHostEnvironment, ILogger<AddProductModel> logger, IProductImageRepository productImageRepository)
        {
            _productRepo = productRepository;
            _productImageRepo = productImageRepository;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            Product = await _productRepo.GetById(id);
            ProductImages = await _productImageRepo.GetByProductId(id);
            return Page();
        }
        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            if (!ModelState.IsValid)
                return Page();
            var pathImg = Path.Combine(_webHostEnvironment.WebRootPath, "Images/Products");
            if (!Directory.Exists(pathImg))
            {
                Directory.CreateDirectory(pathImg);
            }
            if (Image != null)
                if (Image.Length > 0)
                    try
                    {
                        var uniqueFileName = string.Concat(Guid.NewGuid().ToString(), Image.FileName);
                        using var fileStream = new FileStream(Path.Combine(pathImg, uniqueFileName), FileMode.Create);
                        //delete old product image
                        var imgPath = _productRepo.GetById(id).Result.ImageUrl;
                        var prodImg = new FileInfo(Path.Combine(_webHostEnvironment.WebRootPath, imgPath));
                        prodImg.Refresh();
                        if (prodImg.Exists)
                        {
                            prodImg.Delete();
                            _logger.LogInformation($"File Deleted {prodImg.Name}");
                        }
                        Product.ImageUrl = Path.Combine("Images/Products", uniqueFileName);
                        await Image.CopyToAsync(fileStream);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex.Message);
                    }


            await _productRepo.Update(id, Product, User);
            var result = await OnGetAsync(id);
            return result;
        }
        public async Task<IActionResult> OnPostAddImagesAsync()
        {
            var pathCtl = Path.Combine(_webHostEnvironment.WebRootPath, "Images/CatalogImages");
            //if (!ModelState.IsValid)
            //    return Page();
            //CatalogImages = (IFormFileCollection)Request.Form["ctl_Images"].ToList();

            try
            {
                ProductImages = new List<ProductImageViewModel>();
                foreach (var image in CatalogImages)
                {
                    var uniqueFileName = string.Concat(Guid.NewGuid().ToString(), image.FileName);
                    using var fileStream = new FileStream(Path.Combine(pathCtl, uniqueFileName), FileMode.Create);
                    var productImage = new ProductImageViewModel
                    {
                        ImageUrl = Path.Combine("Images/CatalogImages", uniqueFileName),
                        ProductId = Product.Id,
                    };
                    await image.CopyToAsync(fileStream);
                    ProductImages.Add(productImage);
                }
                foreach (var item in ProductImages)
                {
                    await _productImageRepo.Add(item, User);
                }

                var result = await OnPostRefreshImagesAsync(Product.Id);
                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return Page();
                throw ex;
            }
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var prodId = _productImageRepo.GetById(id).Result.ProductId;
            var ctlImagePath = _productImageRepo.GetById(id).Result.ImageUrl;

            try
            {
                await _productImageRepo.RemoveById(id, User);
                var ctlImg = new FileInfo(Path.Combine(_webHostEnvironment.WebRootPath, ctlImagePath));
                ctlImg.Refresh();
                if (ctlImg.Exists)
                {
                    ctlImg.Delete();
                    _logger.LogInformation($"File Deleted {ctlImg.Name}");
                }

                var result = await OnPostRefreshImagesAsync(prodId);
                return result;

            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return Page();
                throw ex;
            }
        }
        public async Task<IActionResult> OnPostRefreshImagesAsync(int id)
        {

            var productImages = await _productImageRepo.GetByProductId(id);
            var result = new PartialViewResult
            {
                ViewName = "~/Pages/Partials/_ProductImagesCardGroup.cshtml",
                ViewData = new ViewDataDictionary<List<ProductImageViewModel>>(ViewData, productImages),
            };
            return result;
        }
    }
}

CompletKitInstall/Pages/Partials/_CatalogImageUpload.cshtml
@using Microsoft.AspNetCore.Http;
@model IFormFileCollection
@{
}
<div id="UploadImages">
    <form asp-page-handler="RefreshImages" id="imageUploadForm" method="post" data-ajax="true" data-ajax-method="post" data-ajax-update="#ProductImages">
        <div class="card-body">
            <h3>Add New Catalog Images</h3>
            <input asp-for="@Model" multiple="multiple" id="ctl_images" name="upload_file" class="form-control" onchange="preview_image();" />
        </div>
        <button class="btn btn-sm btn-primary d-none d-md-inline-block" type="submit" id="AddImages" onclick="clickbtn();">
            Add
        </button>
    </form>
    <div id="image_preview">

    </div>
</div>
<script src="~/js/EditProduct.js"> </script>

               

CompletKitInstall/Pages/Partials/_ProductImagesCardGroup.cshtml
@using CompletKitInstall.ViewModels
@model List<ProductImageViewModel>
@{

}

@if (Model.Count == 0)
{
    <div class="row justify-content-center text-center">
        <div class="col-12 col-md-10 mt-5">

            <i class="fa fa-user fa-5x mb-5"></i>

            <h2>
                No Pictures to show!
            </h2>

            <p class="text-muted">
                You do not have any catalog images for this product yet. Add a new image in the form above.
            </p>
        </div>
    </div> <!-- / .row -->
}
else
{
    <div class="row row-cols-1 row-cols-md-5 g-4 mt-2">
        @foreach (var item in Model)
        {
            <div class="col my-1">
                <div class="card prodcard h-100">
                    <img class="card-img-top rounded" src="~/@item.ImageUrl" alt="Card image cap">
                    <div class="card-body"></div>
                    <div class="card-footer">
                        <form asp-page-handler="delete" asp-route-id="@item.Id" method="post" data-ajax="true" data-ajax-update="#ProductImages">
                            <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}